import React from "react";
import ReactPlayer from 'react-player';
import GlitchText from 'react-glitch-effect/core/GlitchText';
import Ticket_Normal from "../../assets/Ticket_Normal.mp4";
import LazyLoad from 'react-lazyload';

export default function Vision() {

    return (
        <section id="vision">
            <div className="vision-title">
                <GlitchText duration="5000" color2="#00FFFF" color1="red">
                    THE VISION
                </GlitchText>
            </div>
            <div className="content d-flex mt-4 mb-4 gap-5 align-items-center  flex-column flex-md-row">
                <div className="fs-4 mt-5 mb-5" style={{ flex: 1.3 }}>
                    <p>
                        HIVERSE objective is to build a long-lasting structure for sharing knowledge and producting high quality movies, supported by a community of NFT enthusiats and cinema lovers.
                    </p>
                    <p>
                        By bridging web3 and cinema worlds HIVERSE allows holders to earn a share of royalties generated by the exploitation of HIVERSE movies.
                    </p>
                    <p>
                        By placing the community at the heart of this concept, HIVERSE will become a talent incubator for actors, actresses, directors, screenwriters, and other filmmaking professional careers who will be able to express themselves through HIVERSE productions.
                    </p>
                    <p>
                        HIVERSE aspires to become a recognized filmmaking brand on the international stage.
                    </p>
                </div>
                <LazyLoad height={200}>
                    <ReactPlayer playing={true} muted={true} loop={true} className='react-player' url={Ticket_Normal} />
                </LazyLoad>
            </div>
            <div className="link-class">JOIN DISCORD</div>
        </section>

    );
}

